export const agentSentences = [
  "is making a strategic move",
  "is thinking hard",
  "looks to be deliberating his moves well",
  "is calculating the best approach",
  "is analyzing the situation",
  "is considering all possible options",
  "is evaluating the next move",
  "is formulating a plan",
  "is strategizing their next move",
  "is pondering their options",
  "is weighing the pros and cons",
  "is deep in thought",
  "is assessing the risks",
  "is plotting their strategy",
  "is anticipating the opponent's moves",
  "is surveying the game board",
  "is contemplating their next step",
  "is mulling over the possibilities",
  "is examining different scenarios",
  "is devising a tactical maneuver",
  "is analyzing the battlefield",
  "is strategizing their approach",
  "is carefully considering their options",
  "is calculating the optimal move",
  "is weighing the consequences",
  "is contemplating their next move",
  "is studying the opponent's strategy",
  "is formulating a master plan",
  "is searching for weaknesses",
  "is brainstorming tactics",
  "is envisioning different outcomes",
  "is adjusting their strategy",
  "is evaluating the potential risks",
  "is simulating possible moves",
  "is anticipating the opponent's reactions",
  "is fine-tuning their plan",
  "is focusing on long-term strategy",
  "is exploring alternative approaches",
  "is considering unconventional tactics",
  "is analyzing the game from multiple angles",
];
